spring.application.name=chapter12-3

# ??AI? API ??  ?
server.port=8081
spring.ai.openai.api-key=${OPENAI_API_KEY}

# ???  ???  ???  ??
# Transcription(STT) ??  ??(default)
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json

# TTS ??  ??(default)
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.voice=nova
spring.ai.openai.audio.speech.options.response-format=mp3
spring.ai.openai.audio.speech.options.speed=1.0