spring.application.name=chapter08-1

# server.port ??
server.port=8081

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=1.0
# ??  ??  ???  ???  ??  ??  ??  ??
# logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai=DEBUG