spring.application.name=chapter12-1

server.port=8081

# ??AI API ??  ?
spring.ai.openai.api-key=${OPENAI_API_KEY}

# ?? STT ??  ??
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json