spring.application.name=chapter10-1

# ?  ??  ????
spring.main.web-application-type=none

# MCP ?? ?? ?? ? STDIO ??? ??
spring.ai.mcp.server.name=mcp-server-stdio
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.stdio=true

# ???  ??  ???  ???? : ? ??? ??? ?? ??? JSON ??? ?? ?? ??? ?????.
spring.main.banner-mode=off
logging.pattern.console=

# ??????  ??
spring.datasource.url=jdbc:mysql://localhost:3306/springmcp
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??  ??
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update